service: take-away-backend

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x  
  region: eu-north-1
  environment:
    API_KEY: ${env:API_KEY}  # Hämta API-nyckeln från en miljövariabel

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"

functions:
  getAbout:
    handler: src/handlers/getAbout.handler
    events:
      - httpApi:
          path: /about
          method: get

  getConfirmation:
    handler: src/handlers/getConfirmation.handler
    events:
      - httpApi:
          path: /confirmation
          method: get

  getContact:
    handler: src/handlers/getContact.handler
    events:
      - httpApi:
          path: /contact
          method: get
          
resources:
  Resources:
    MenuTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MenuTable  # DynamoDB-tabellnamn
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

    AboutTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AboutTable  # DynamoDB-tabellnamn
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

    ContactTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ContactTable  # DynamoDB-tabellnamn
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

    ConfirmationTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ConfirmationTable  # DynamoDB-tabellnamn
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

custom:
  serverless-offline:
    cors:
      allowOrigins:
        - "*"  # Tillåter alla origin (kan justeras för säkerhet)
      allowHeaders:
        - Content-Type
        - x-api-key  
      allowMethods:
        - GET   # Endast GET-metod tillåts

