service: take-away-backend

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x  
  region: eu-north-1
  environment:
    API_KEY: ${env:API_KEY}  # API-nyckeln från miljövariabeln

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"

functions:
  getMenu:
    handler: handler.getMenu
    events:
      - httpApi:
          path: /menu
          method: get
          cors: true  # CORS-konfiguration för denna specifika endpoint
  getAbout:
    handler: handler.getAbout
    events:
      - httpApi:
          path: /about
          method: get  
          cors: true

  getConfirmation:
    handler: handler.getConfirmation
    events:
      - httpApi:
          path: /user/confirmation
          method: get
          cors: true
          
  getContact:
    handler: handler.getContact
    events:
      - httpApi:
          path: /contact
          method: get
          cors: true
          
resources:
  Resources:
    MenuTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MenuTable  # DynamoDB-tabellnamn
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

custom:
  serverless-offline:
    cors:
      allowOrigins:
        - "*"  # Tillåter alla origin
      allowHeaders:
        - Content-Type
        - x-api-key  
      allowMethods:
        - GET   # Endast GET-metod för CORS
