service: take-away-backend

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x  
  region: eu-north-1
  environment:
    API_KEY: ${env:API_KEY}  # Hämta API-nyckeln från en miljövariabel

  httpApi:
    cors:
      allowedOrigins:
        - "*"  # Tillåter alla origin (kan specificeras om säkerhet behövs)
      allowedHeaders:
        - Content-Type
        - x-api-key
      allowedMethods:
        - GET  # Tillåt endast GET-metoder

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/MenuTable"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/AboutTable"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/ContactTable"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/ConfirmationTable"

functions:
  getMenu:
    handler: handler.getMenu
    events:
      - httpApi:
          path: /menu
          method: get

  getAbout:
    handler: handler.getAbout
    events:
      - httpApi:
          path: /about
          method: get

  getConfirmation:
    handler: handler.getConfirmation
    events:
      - httpApi:
          path: /confirmation
          method: get

  getContact:
    handler: handler.getContact
    events:
      - httpApi:
          path: /contact
          method: get
          
resources:
  Resources:
    MenuTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MenuTable  # DynamoDB-tabellnamn
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

    AboutTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AboutTable  # DynamoDB-tabellnamn
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

    ContactTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ContactTable  # DynamoDB-tabellnamn
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

    ConfirmationTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ConfirmationTable  # DynamoDB-tabellnamn
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

custom:
  serverless-offline:
    cors:
      allowOrigins:
        - "*"  # Tillåter alla origin (kan justeras för säkerhet)
      allowHeaders:
        - Content-Type
        - x-api-key  
      allowMethods:
        - GET   # Endast GET-metod tillåts

